### ISSUE TITLE
Console dumps

### ISSUE THREAD

**Issue by MaximBalaganskiy** [oricalvo/systemjs-cachebuster#1]
Could you please consider making debug console messages configurable?

**Comment by oricalvo** [comment]
Sure. Just give me some samples so I understand better the desired logs

**Comment by MaximBalaganskiy** [comment]
The existing are fine, I would just make them optional. May be an attribute on a `script` tag could indicate that I want logging, otherwise by default it would be silent

**Comment by oricalvo** [comment]
OK. I will handle that. Give me a day or two.

**Comment by MaximBalaganskiy** [comment]
:+1: no rush, just a little improvement

**Comment by oricalvo** [comment]
Fixed. Now, by default logs are disabled. You can re-enable them using SystemCacheBuster.config({enableLogs: true})
