### ISSUE TITLE
Error with crypto

### ISSUE THREAD

**Issue by wburgers** [oricalvo/systemjs-cachebuster#2]
Hi, I'm getting the following error:

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:67:16)
    at SystemJSCacheBuster._processFile (C:\Project\node_modules\systemjs-cachebuster\src\system.cachebuster.gulp.js:36:42)
    at Transform.FileHashTransform.write (C:\Project\node_modules\systemjs-cachebuster\src\system.cachebuster.gulp.js:63:16)
...

Furthermore the crypto library looks pretty much deprecated.
(last update 5 years ago is pretty dangerous for a crypto library...)
Why do you still use that library?

**Comment by wburgers** [comment]
Ah nevermind, I specified the folder instead of the files...

**Comment by oricalvo** [comment]
BTW, which crypto library do you recommend ?

**Comment by wburgers** [comment]
From a security perspective, I don't trust crypto libraries that haven't been updated in 5 years.
Not that it matters that much for the calculation of a cache-busting hash, but still...

searching npm for crypto libraries, there are not many great alternatives.
https://www.npmjs.com/package/crypto-js this one looks a little more promising and at least is still maintained.

https://www.npmjs.com/package/crypto-lite
https://www.npmjs.com/package/crypto-lib
https://www.npmjs.com/package/native-crypto
These look more active as well.
Not sure if the last one is just a wrapper for crypto, but it doesn't look like it.
